# Generated by Django 4.1.7 on 2023-03-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('title',)},
        ),
    ]
